<template>
  <li>
    <h3>{{ topicName }}</h3>
    <p>{{ description }}</p>
    <!-- <button @click="$emit('select-topic', id)">Learn More</button> -->
    <button @click="activateTopic(id)">Learn More</button>
  </li>
</template>

<script>
export default {
  props: ['id', 'topicName', 'description'],
  // Data modification is achieved by injecting methods provide by upper-level components
  // which solves the redundant code generated by multi-layer event transmission
  inject: ['activateTopic'],
};
</script>
